ComplianceAsCode/redhat

openshift-container-platform-3/policies/AC-Access_Control/component.yaml

Line break in the middle of the url is little less common. So, it tends to break
parser that tries to render link nicely in github.com/RedHatGov/ocdb

Fix broken link

---

openstack-platform-13/policies/MA-Maintenance/component.yaml

Based on https://github.com/ComplianceAsCode/redhat-openstack-platform-13/issues/436 it seems that MA-6 (4) was confused with MA-4 (6).

Remove MA-6 (4) it does not (yet) exists

---

openshift-container-platform-3/policies/AC-Access_Control/component.yaml

These characters seems to be present only by accident. Nevertheless, they break parsing this text as MDX Markdown.

Remove overabundant > and < characters

---

openshift-dedicated/policies/IR-Incident_Response/component.yaml

The file is called IR-Incident_Response and hence it should contain information
about incident response, not about maintenance.
Interestingly, this problem exists only in master branch, it has been already
fixed in opencontrol branch.

Clean a left-over this file was probably copied over, but not edited

---

coreos-4/policies/AC-Access_Control/component.yaml
openshift-container-platform-3/policies/AC-Access_Control/component.yaml
openshift-container-platform-3/policies/AU-Audit_and_Accountability/component.yaml
openshift-container-platform-3/policies/SC-Systems_and_Communications_Protection/component.yaml
openshift-container-platform-4/policies/AC-Access_Control/component.yaml
openshift-container-platform-4/policies/AU-Audit_and_Accountability/component.yaml
openshift-container-platform-4/policies/SC-Systems_and_Communications_Protection/component.yaml
openstack-platform-13/policies/SC-Systems_and_Communications_Protection/component.yaml

Req. 1 is actually child of some subsection; and hence we should mark it as such.
Although, current open control file format does not allow us to specify childs
of subsection we can workaround this by repeating the subsection identifier in
the key.
Addressing error when converting opencontrols to oscal.
Following error was found during validation of oscal:
```
coreos-4.xml:828: element statement: Schemas validity error : Element '{http://csrc.nist.gov/ns/oscal/1.0}statement', attribute 'statement-id': 'ac-8_smt.Req. 1' is not a valid value of the atomic type 'xs:NCName'.
coreos-4.xml:828: element statement: Schemas validity error : Element '{http://csrc.nist.gov/ns/oscal/1.0}statement', attribute 'statement-id': Warning: No precomputed value available, the value was either invalid or …
```

Rework how we handle composite control responses

---

openshift-container-platform-4/policies/AC-Access_Control/component.yaml

Addressing failure when converting this to oscal.
```
$ oscalkit convert opencontrol https://github.com/ComplianceAsCode/redhat output/
$ oscalkit validate output/*
output/openshift-container-platform-4.xml:47: element statement: Schemas validity error : Element '{http://csrc.nist.gov/ns/oscal/1.0}statement', attribute 'statement-id': 'ac-1_stmt.b AC-1(b) is an organizational control outside the scope of OpenShift configuration.' is not a valid value of the atomic type 'xs:NCName'.
output/openshift-container-platform-4.xml:47: element statement: Schemas validity error : Element '{http://csrc.nist.gov/ns/oscal/1.0}statement', attribute 'statement-id': Warning: No precomputed value available, the value was either invalid or something strange happend. …
```

Add missing yaml attribute

---

virtualization-host/policies/CA-Security_Assessment_and_Authorization/component.yaml

One instance is more than enough.
Addressing:
$ oscalkit convert opencontrol https://github.com/ComplianceAsCode/redhat output/
$ oscalkit validate output/*
output/virtualization-host.xml:860: element statement: Schemas validity error : Element '{http://csrc.nist.gov/ns/oscal/1.0}statement': Duplicate key-sequence ['ca-7_stmt.c'] in unique identity-constraint '{http://csrc.nist.gov/ns/oscal/1.0}implemented-requirement-statement-keys'.
output/virtualization-host.xml fails to validate

No need to define CA-7 (c) twice

---

coreos-4/policies/CM-Configuration_Management/component.yaml
openshift-container-platform-4/policies/CM-Configuration_Management/component.yaml

Status and text update.
Control is organizational, NIST status is not applicable. Demonstration of efficacy of this control is the sole responsibility of the client, even if the implemented COS/OCP system(s) is/are defined by the client to be in scope.

OCP COS CM-4(2)

---

openshift-container-platform-4/policies/SC-Systems_and_Communications_Protection/component.yaml

We'll use this in our automation to detect whether works needs to be
done (or not).

OCP4: Add comments to responses to indicate that the platform meets the control by default

---

openshift-container-platform-4/policies/SC-Systems_and_Communications_Protection/component.yaml

I marked it as not applicable since it's out of scope for OpenShift
itself to configure the DNS entries that are exposed to external
clients. That is done as part of the cloud configuration (e.g. via
Route53).

OCP4: Add response for SC-20

---

openshift-container-platform-4/policies/AC-Access_Control/component.yaml

Mostly easy
OCP: AC-6(9) is inherently met
What constitutes an action by an admin role must be synthetized in a SIEM.
The audit logs do specify the RBAC rule that allowed the action and the
identity that requested the action.
OCP: AC-6(2) and (5) are organizational controls
The only thing we can do is to prevent kubeadmin from being used by 
multiple people.
OCP: AC-6, -6(1) and and -6(10) are inherently met
In all three cases, RBAC, SCC and for 6(1) the cluster-admin role in
particular are enabled by default and neither RBAC or SCC are optional.

OCP: AC-6 clarifications

---

openshift-container-platform-4/policies/AC-Access_Control/component.yaml

Marking as WIP because I wasn't sure about some things..
For a) I think the reply is good. For b) I wasn't sure if just displaying
a banner during a log in with "oc login" or customizing the login page is
enough because the control says the banner is to be retained on the screen
until the user acknowledges it.
I left out any reply to c) for now -- honestly I think just copying the same
would make the most sense, but I wanted to double-check first.

WIP: OCP: AC-8 is covered by configuring a login banner and motd for the oc tool

---

openshift-container-platform-4/policies/AC-Access_Control/component.yaml

- delete comments about obsolete versions
- remove the mention of firewalld, there's no firewalld on RHCOS
- AC-17(3) is inherently met by capabilities of OCP

OCP AC-17: Delete all oauth tokens

---

openshift-container-platform-4/policies/AU-Audit_and_Accountability/component.yaml

The control response was already good, this just adds the blob expected
by our parser script.

OCP: AU-8 is inherently met

---

openshift-container-platform-4/policies/AU-Audit_and_Accountability/component.yaml

The control says: The information system protects audit information and
audit tools from unauthorized access, modification, and deletion.
CaC rule to check the log permissions and ownership is planned with 
https://issues.redhat.com/browse/CMP-972 and a rule to check the TLS
outputs when forwarding is planned with
https://issues.redhat.com/browse/CMP-973
Also mark 9(4) as organizational control.

OCP: AU-9: audit logs are protected by OS permissions and TLS in-transit

---

openshift-container-platform-4/policies/AU-Audit_and_Accountability/component.yaml

The control says:
The organization retains audit records for [Assignment:
organization-defined time period consistent with records retention
policy] to provide support for after-the-fact investigations of security
incidents and to meet regulatory and organizational information
retention requirements.
This is not really possible with the retention options that the API
servers themselves offer, so the logs must be forwarder off the cluster
for retention.

AU-11: log retention is provided by offloading logs off-cluster

---

openshift-container-platform-4/policies/AU-Audit_and_Accountability/component.yaml

The control says:
“The information system off-loads audit records [Assignment:
organization-defined frequency] onto a different system or media than
the system being audited.”
The CaC rule will be labeled as appripriate

OCP: AU-4(1): Offloading of logs is achieved with CLO

---

openshift-container-platform-4/policies/IA-Identification_and_Authentication/component.yaml

The control says:
The organization requires individuals to be authenticated with an
individual authenticator when a group authenticator is employed.
The best way to ensure the control is met is through removing kubeadmin
and setting up an IDP, then all user identities can be tied into OCP
identities and no group authentication is performed at all.

IA-2(5): No group authenticators except for kubeadmin, let's remove kubeadmin

---

openshift-container-platform-4/policies/AU-Audit_and_Accountability/component.yaml

This makes the control inherently met. A follow up ticket to see
if we need to refine the reply with respect to the process tracking
is https://issues.redhat.com/browse/CMP-976

OCP4: AU-2: Auditing is enabled by default and cannot be disabled

---

openshift-container-platform-4/policies/AU-Audit_and_Accountability/component.yaml

A further improvement is planned:
https://issues.redhat.com/browse/CMP-965
We need to write the PrometheusRule to issue alerts on audit write
errors as well as figure out if we need a configurable action in case
the audit write fails other than some example webhook.
I've reached out to the OSD folks to get their take on the control.

OCP: AU-5: Improve response audit write errors

---

openshift-container-platform-4/policies/MA-Maintenance/component.yaml

MA-4(c) says:
Employs strong authenticators in the establishment of nonlocal
maintenance and diagnostic sessions
MA-4(e) says:
Terminates session and network connections when nonlocal maintenance is
completed.
Now the way I read the control is that it is meant more for devices or
appliances where you can expect the vendor to log in remotely. In OCP,
there is no concept of a maintenance access, so the best we can do which
IMO covers the control is to require the use of an IDP and remove the
kubeadmin account so that everything is properly audited and tied to
IDP identities.

MA-4: Just like regular auth

---

openshift-container-platform-4/policies/IA-Identification_and_Authentication/component.yaml

The control itself says:
Replay- resistant techniques include, for example, protocols that use
nonces or challenges such as Transport Layer Security (TLS) and time
synchronous or challenge-response one-time authenticators.
So as long as we enfornce the use of TLS, we should be good.

IA-2(8): OCP authentication is replay-resistant as long as TLS is enforced

---

openshift-container-platform-4/policies/AU-Audit_and_Accountability/component.yaml

OCP4: AU-3(1): custom audit policies are not supported, but the
WriteRequestBodies should satisfy the control
We'll follow up with https://issues.redhat.com/browse/CMP-974
OCP4: AU-3 is inherently met
All the required events are audited by default with all the profiles.

OCP4: replies to AU-3, 3(1)

---

openshift-container-platform-4/policies/IA-Identification_and_Authentication/component.yaml

Outside the cluster it's up to the deployment

OCP4: IA-3: mTLS is used inside the cluster from bootstrap onwards

---

openshift-container-platform-4/policies/AC-Access_Control/component.yaml

Setting up a bastion host is outside the scope of OCP configuration.

OCP4: AC-17(2) is not applicable to openshift

---

openshift-container-platform-4/policies/SA-System_and_Services_Acquisition/component.yaml

This blob will be used by our documentation to mark the control as not
needing additional work.

OCP SA: Add a blob that explicitly says that a control is addressed via documenattion

---

openshift-container-platform-4/policies/CM-Configuration_Management/component.yaml

The organization:
a. Establishes [Assignment: organization-defined policies] governing the installation of software by users;
b. Enforces software installation policies through [Assignment: organization-defined methods]; and
c. Monitors policy compliance at [Assignment: organization-defined frequency].
Regarding the monitoring, the control says: "Policy enforcement methods
include procedural methods (e.g., periodic examination of user accounts),
automated methods (e.g., configuration settings implemented on organizational
information systems), or both." which makes me think that periodically running
the checks that look if signing is enforced and if registries have been
configured is enough. It would be nice to write the openscap rule so that
the list of allowed registries is …

OCP4: CM-11: User-installed software

---

openshift-container-platform-4/policies/SA-System_and_Services_Acquisition/component.yaml
openshift-container-platform-4/policies/SC-Systems_and_Communications_Protection/component.yaml

- SA-10 was missing the blob
- SC-22 was not marked as complete, which the dashboard script expects

Tag SA-10 and SC-22 as inherently met

---

openshift-container-platform-4/policies/IA-Identification_and_Authentication/component.yaml

For the full discussion, see https://issues.redhat.com/browse/CMP-983
the tl;dr is that this control seems to be a superset of SC-12 and SC-13.
For this control in particular, requiring FIPS seems like the best thing
to do and is agreed on by the most people.

OCP4: IA-7 is met with FIPS enabled
