ComplianceAsCode/redhat

- ansible-tower/policies/IA-Identification_and_Authentication/component.yaml
resolves https://github.com/ComplianceAsCode/redhat/issues/320
> Authentication Responses

- openshift-container-platform-3/policies/AC-Access_Control/component.yaml
- openshift-container-platform-3/policies/AT-Awareness_and_Training/component.yaml
- openshift-container-platform-3/policies/AU-Audit_and_Accountability/component.yaml
- openshift-container-platform-3/policies/CA-Security_Assessment_and_Authorization/component.yaml
- openshift-container-platform-3/policies/CM-Configuration_Management/component.yaml
- openshift-container-platform-3/policies/CP-Contingency_Planning/component.yaml
- openshift-container-platform-3/policies/IA-Identification_and_Authentication/component.yaml
- openshift-container-platform-3/policies/IR-Incident_Response/component.yaml
- openshift-container-platform-3/policies/MA-Maintenance/component.yaml
- openshift-container-platform-3/policies/MP-Media_Protection/component.yaml
- openshift-container-platform-3/policies/PL-Planning/component.yaml
- openshift-container-platform-3/policies/PS-Personnel_Security/component.yaml
- openshift-container-platform-3/policies/RA-Risk_Assessment/component.yaml
- openshift-container-platform-3/policies/SA-System_and_Services_Acquisition/component.yaml
- openshift-container-platform-3/policies/SC-Systems_and_Communications_Protection/component.yaml
- openshift-container-platform-3/policies/SI-System_and_Information_Integrity/component.yaml
To conform with opencontrol schema
> change implementation_status from "Not applicable" to "not applicable"

- openshift-container-platform-3/policies/CP-Contingency_Planning/component.yaml
- resolves https://github.com/ComplianceAsCode/redhat/issues/663
- resolves https://github.com/ComplianceAsCode/redhat/issues/662
- resolves https://github.com/ComplianceAsCode/redhat/issues/661
- resolves https://github.com/ComplianceAsCode/redhat/issues/660
- resolves https://github.com/ComplianceAsCode/redhat/issues/659
- resolves https://github.com/ComplianceAsCode/redhat/issues/658
- resolves https://github.com/ComplianceAsCode/redhat/issues/657
- resolves https://github.com/ComplianceAsCode/redhat/issues/656
- resolves https://github.com/ComplianceAsCode/redhat/issues/655
> Update CP Control family answers

- virtualization-host/policies/CM-Configuration_Management/component.yaml
- virtualization-host/policies/IA-Identification_and_Authentication/component.yaml
- virtualization-host/policies/SA-System_and_Services_Acquisition/component.yaml
- resolves https://github.com/ComplianceAsCode/redhat/issues/513
- resolves https://github.com/ComplianceAsCode/redhat/issues/514
- resolves https://github.com/ComplianceAsCode/redhat/issues/515
- resolves https://github.com/ComplianceAsCode/redhat/issues/518
- resolves https://github.com/ComplianceAsCode/redhat/issues/519
- resolves https://github.com/ComplianceAsCode/redhat/issues/520
- resolves https://github.com/ComplianceAsCode/redhat/issues/527
- resolves https://github.com/ComplianceAsCode/redhat/issues/528
- resolves https://github.com/ComplianceAsCode/redhat/issues/529
- resolves https://github.com/ComplianceAsCode/redhat/issues/530
- resolves https://github.com/ComplianceAsCode/redhat/issues/531
- resolves https://github.com/ComplianceAsCode/redhat/issues/532
- resolves …
> RHV FISMA Low, part 2

- virtualization-host/policies/SC-Systems_and_Communications_Protection/component.yaml
- resolves https://github.com/ComplianceAsCode/redhat/issues/585
- resolves https://github.com/ComplianceAsCode/redhat/issues/587
- resolves https://github.com/ComplianceAsCode/redhat/issues/588
- resolves https://github.com/ComplianceAsCode/redhat/issues/589
- resolves https://github.com/ComplianceAsCode/redhat/issues/590
- resolves https://github.com/ComplianceAsCode/redhat/issues/591
- resolves https://github.com/ComplianceAsCode/redhat/issues/593
- resolves https://github.com/ComplianceAsCode/redhat/issues/594
> RHVH FISMA Low, Part 3

- openshift-dedicated/policies/PE-Physical_and_Environmental_Protection/component.yaml
- resolves https://github.com/ComplianceAsCode/redhat/issues/780
- resolves https://github.com/ComplianceAsCode/redhat/issues/779
- resolves https://github.com/ComplianceAsCode/redhat/issues/778
- resolves https://github.com/ComplianceAsCode/redhat/issues/777
- resolves https://github.com/ComplianceAsCode/redhat/issues/776
- resolves https://github.com/ComplianceAsCode/redhat/issues/775
- resolves https://github.com/ComplianceAsCode/redhat/issues/774
- resolves https://github.com/ComplianceAsCode/redhat/issues/773
- resolves https://github.com/ComplianceAsCode/redhat/issues/772
- resolves https://github.com/ComplianceAsCode/redhat/issues/771
- resolves https://github.com/ComplianceAsCode/redhat/issues/770
- resolves https://github.com/ComplianceAsCode/redhat/issues/769
- resolves …
> OSD FedRAMP - Complete PE controls

- ansible-tower/policies/IR-Incident_Response/component.yaml
- coreos-4/policies/IR-Incident_Response/component.yaml
- identity-management/policies/IR-Incident_Response/component.yaml
> Remove duplicate item.

- openstack-platform-13/policies/AU-Audit_and_Accountability/component.yaml
We will have warnings for this kind of problems on the site:
https://github.com/isimluk/ocdb/commit/230ab4b4be9ec8e27c2e96b4465ba751bdbe4236
> Another typo found

- osp13/osp13.yaml
These changes were made in master branch of osp13, but they are missing in opencontrol branch.
> Add missing changes

- ocp3/ocp3.yaml
> Fix the broken link

- .github/workflows/build.yml
- Makefile
- build/ansible-tower/component.yaml
- build/coreos-4/component.yaml
- build/identity-management/component.yaml
- build/openshift-container-platform-3/component.yaml
- build/openshift-dedicated/component.yaml
- build/openstack-platform-13/component.yaml
- build/virtualization-host/component.yaml
- build/virtualization-manager/component.yaml
- opencontrol.yaml
This brings
- Good Makefile, that allows anyone to just run `make all` locally to have the repository re-built.
- Github actions settings file that runs `make clean all` and submits PR automatically, when needed.
To show off, I have enabled Github Actions on my own fork, so when I pushed commit to my forked repo at https://github.com/isimluk/complianceAsCode_redhat/commit/9173554620db64d3cf1f307653c5f2ba2eeae3b0 then new PR was opened automatically to update composed files: https://github.com/isimluk/complianceAsCode_redhat/pull/2
> Automated build using github actions

- Makefile
- opencontrol.yaml
- Add OCP4 to the automated build
- advertise existence of OCP4 in the opencontrol index file
> OCP4 build

- coreos-4/policies/AC-Access_Control/component.yaml
- openshift-container-platform-4/policies/AC-Access_Control/component.yaml
For more details see: https://github.com/isimluk/complianceAsCode_redhat/blob/0bf3e452f2fbb2e2da714b4ecbe0751ade2ca700/coreos-4/policies/AC-Access_Control/component.yaml#L5-L11
> Replace implementation_status implemented with complete

- ansible-tower/policies/AT-Awareness_and_Training/component.yaml
- coreos-4/policies/AT-Awareness_and_Training/component.yaml
- coreos-4/policies/SA-System_and_Services_Acquisition/component.yaml
- identity-management/policies/AT-Awareness_and_Training/component.yaml
- openshift-container-platform-3/policies/AT-Awareness_and_Training/component.yaml
- openshift-container-platform-4/policies/AT-Awareness_and_Training/component.yaml
- openstack-platform-13/policies/AT-Awareness_and_Training/component.yaml
- virtualization-host/policies/AT-Awareness_and_Training/component.yaml
- virtualization-manager/policies/AT-Awareness_and_Training/component.yaml
- Everything is still not applicable
- Updated answers to reflect control breakouts, eg AT-1(a), AT-1(b)
> Update AT templates for all products

- .github/workflows/build.yml
I think we have reviewed enough automated prs already.
For more info, see discussion at the bottom of #1046.
> Github Actions to not create PR for automated build changes

- coreos-4/policies/AC-Access_Control/component.yaml
- coreos-4/policies/CA-Security_Assessment_and_Authorization/component.yaml
- coreos-4/policies/CM-Configuration_Management/component.yaml
- openshift-container-platform-4/policies/AC-Access_Control/component.yaml
- openshift-container-platform-4/policies/CA-Security_Assessment_and_Authorization/component.yaml
- openshift-container-platform-4/policies/CM-Configuration_Management/component.yaml
- jira.coreos.com has been migrated to issues.redhat.com
> Update JIRA links

- coreos-4/policies/AC-Access_Control/component.yaml
> Add Missing text attribute

- openshift-container-platform-4/policies/AC-Access_Control/component.yaml
Peer reviewed by:
* @kevindoingbizas
> ocp4 - AC-2 (1) - mark as complete and update narrative

- openshift-container-platform-4/policies/AC-Access_Control/component.yaml
peer reviewed by:
* @kevindoingbizas
> ocp 4 - AC-2 (3) - mark as complete

- openshift-container-platform-4/policies/AC-Access_Control/component.yaml
peer reviewed by:
* @kevindoingbizas
> OCP 4 - AC-2 (2) - mark as complete and update narrative

- openshift-container-platform-4/policies/AC-Access_Control/component.yaml
peer reviewed
* kevindoingbizas
> ocp4 - AC-2 (13) - mark as not applciable

- openshift-container-platform-4/policies/SI-System_and_Information_Integrity/component.yaml
Peer reviewers:
Needs review
Update SI-2(1) to reflect organizational responsibility (not applicable)
> SI-2(1) - Central Management

- coreos-4/policies/RA-Risk_Assessment/component.yaml
- openshift-container-platform-4/policies/RA-Risk_Assessment/component.yaml
> Update RA controls

- coreos-4/policies/PS-Personnel_Security/component.yaml
- openshift-container-platform-4/policies/PS-Personnel_Security/component.yaml
> Update PS Controls

- coreos-4/policies/SA-System_and_Services_Acquisition/component.yaml
- coreos-4/policies/SI-System_and_Information_Integrity/component.yaml
- openshift-container-platform-4/policies/SA-System_and_Services_Acquisition/component.yaml
- openshift-container-platform-4/policies/SI-System_and_Information_Integrity/component.yaml
:flashlight: :scissors: :hocho: :fire: :toilet: :droplet: :relaxed:
> Remove dupes or amend id to avoid dupes

- .github/workflows/validate-pr.yaml
So we avoid, duplicates and other issues.
> Validate opencontrol content

- openshift-container-platform-4/policies/SC-Systems_and_Communications_Protection/component.yaml
The response for SC-7(7) was actually for SC-7(8) and I added the response for SC-7(7)
> SC-7(7) and SC-7(8)

- openshift-container-platform-4/policies/AC-Access_Control/component.yaml
peer reviewed by:
* kevindoingbizas
> ocp4 - AC-2 (11) - mark as not applicable

- openshift-container-platform-4/policies/AU-Audit_and_Accountability/component.yaml
Peer reviewed:
- mtclemente
- dwinchell
> AU-6 (all) updated status and narrative

- coreos-4/header_opencontrol.yaml
> Rename coreos component

- coreos-4/policies/MA-Maintenance/component.yaml
- openshift-container-platform-4/policies/MA-Maintenance/component.yaml
Status unchanged, still not applicable. Added documentation to supplement client organization satisfaction efforts.
> COS OCP MA-6(1)

- openshift-container-platform-4/policies/SI-System_and_Information_Integrity/component.yaml
> ocp4: SI-4 (13): Response status should match our prose

- openshift-container-platform-4/policies/SI-System_and_Information_Integrity/component.yaml
> Response status should match our prose

- .github/workflows/validate-pr.yaml
This will may improve contributors ability to identify cause of
failures.
> Run CI not only on PRs, but also on master branch

- openshift-container-platform-4/policies/SC-Systems_and_Communications_Protection/component.yaml
- openshift-container-platform-4/policies/SI-System_and_Information_Integrity/component.yaml
- virtualization-host/policies/CP-Contingency_Planning/component.yaml
- virtualization-host/policies/IA-Identification_and_Authentication/component.yaml
- virtualization-host/policies/SA-System_and_Services_Acquisition/component.yaml
- virtualization-host/policies/SC-Systems_and_Communications_Protection/component.yaml
- virtualization-host/policies/SI-System_and_Information_Integrity/component.yaml
- virtualization-manager/policies/CP-Contingency_Planning/component.yaml
- virtualization-manager/policies/IA-Identification_and_Authentication/component.yaml
- virtualization-manager/policies/SA-System_and_Services_Acquisition/component.yaml
- virtualization-manager/policies/SC-Systems_and_Communications_Protection/component.yaml
- virtualization-manager/policies/SI-System_and_Information_Integrity/component.yaml
- Fix some OCP bugs
- Fix some CP bugs for RHV content
> Update IA, SA, SC, and SI for RHV

- openshift-container-platform-4/policies/CA-Security_Assessment_and_Authorization/component.yaml
peer reviewed by:
* @kevindoingbizas
> ocp4 - ca-5 (all) - changing from partial to not applicable and updating narrative

- coreos-4/policies/SC-Systems_and_Communications_Protection/component.yaml
Added language to COS SC-7(7) mirrored from Michael Radecker's update to OCP SC-7(7).
> Cos sc 7(7)

- coreos-4/policies/RA-Risk_Assessment/component.yaml
- openshift-container-platform-4/policies/RA-Risk_Assessment/component.yaml
> Ocp cos ra 5(5)

- openshift-container-platform-4/policies/CA-Security_Assessment_and_Authorization/component.yaml
Reviewed all CA items and updated CA-9 (1) to reflect that the control is applicable but a solution has not been determined yet and discussions are ongoing. @mertel-rh
> Update CA-9 (1)

- coreos-4/policies/CP-Contingency_Planning/component.yaml
- openshift-container-platform-4/policies/CP-Contingency_Planning/component.yaml
- Add link for nodes in RHCOS CP-10 as well
> Update CP-9 information for RHCOS and OCP

- coreos-4/policies/SI-System_and_Information_Integrity/component.yaml
- openshift-container-platform-4/policies/SI-System_and_Information_Integrity/component.yaml
- Fix setting implementation_status for SI-4
> Update SI-5 for CoreOS and OCP4

- coreos-4/policies/CM-Configuration_Management/component.yaml
- openshift-container-platform-4/policies/CM-Configuration_Management/component.yaml
> Update CM-5, CM-2(3), and CM-8(1) for RHCOS and OCP4

- rhacm/policies/AC-Access_Control/component.yaml
Quick PR to change extension which is causing online information to not be shown properly
> Fixing file ext from yml to yaml..apparently we expect .yaml

- rhacm/policies/AC-Access_Control/component.yaml
@redhatrises let me know if this is a better approach.
> Updates to AC controls for RHACM

- rhacm/opencontrol.yaml
- rhacm/policies/SC-Systems_and_Communications_Protection/component.yaml
Added SC to opencontrol.yaml as well
> Adding SC controls for RHACM

- rhacm/opencontrol.yaml
- rhacm/policies/SA-System_and_Services_Acquisition/component.yaml
> Adding SA controls for RHACM

- openshift-container-platform-4/policies/RA-Risk_Assessment/component.yaml
The Compliance Operator is the answer.
> OCP4: Update the response to RA-5

- openshift-container-platform-4/policies/SC-Systems_and_Communications_Protection/component.yaml
Namespaces and RBAC are the answer.
> OCP4: Add responses for SC2

- openshift-container-platform-4/policies/SC-Systems_and_Communications_Protection/component.yaml
> OCP4: Add responses for SC-3

- openshift-container-platform-4/policies/SC-Systems_and_Communications_Protection/component.yaml
> Add response for SC-4

- openshift-container-platform-4/policies/SC-Systems_and_Communications_Protection/component.yaml
> OCP4: Add response for SC-6

- openshift-container-platform-4/policies/SC-Systems_and_Communications_Protection/component.yaml
> OCP4: Add responses for SC-5

- openshift-container-platform-4/policies/SC-Systems_and_Communications_Protection/component.yaml
> OCP4: Add response for SC-19

- openshift-container-platform-4/policies/SC-Systems_and_Communications_Protection/component.yaml
Can be met using the OAuth server's configuration.
> OCP4: Add response for SC-10

- openshift-container-platform-4/policies/SC-Systems_and_Communications_Protection/component.yaml
> OCP4: Add response to SC-13

- openshift-container-platform-4/policies/SC-Systems_and_Communications_Protection/component.yaml
> OCP4: Add response for SC-23

- openshift-container-platform-4/policies/SC-Systems_and_Communications_Protection/component.yaml
> OCP4: Add response for SC-28 and SC-28(1)

- openshift-container-platform-4/policies/SC-Systems_and_Communications_Protection/component.yaml
> OCP4: Add response for SC-17

- openshift-container-platform-4/policies/SC-Systems_and_Communications_Protection/component.yaml
This ensures that our automation marks that as met.
> OCP4: Amend response for SC-39

- openshift-container-platform-4/policies/AC-Access_Control/component.yaml
The corresponding CaC link is
https://github.com/ComplianceAsCode/content/pull/7003
> OCP4: AC-7 is satisfied with IDP

- openshift-container-platform-4/policies/SC-Systems_and_Communications_Protection/component.yaml
> OCP4: Add resonse to SC-22

- openshift-container-platform-4/policies/SI-System_and_Information_Integrity/component.yaml
This references OpenShift's monitoring stack.
> OCP4: Add responses for SC-I(1) and (2)

- openshift-container-platform-4/policies/SI-System_and_Information_Integrity/component.yaml
> OCP4: Add response for SI-4(16)

- openshift-container-platform-4/policies/SI-System_and_Information_Integrity/component.yaml
> OCP4: Add responses for SI-7 and SI-7(1)

- openshift-container-platform-4/policies/SC-Systems_and_Communications_Protection/component.yaml
> OCP4: Add repsonse for SC-23(1)

- openshift-container-platform-4/policies/SI-System_and_Information_Integrity/component.yaml
This is so it gets picked up by our automation.
> OCP4: Add "inherently meets" to SI-11

- openshift-container-platform-4/policies/CM-Configuration_Management/component.yaml
Given the nature of OpenShift, I responded that this is inherently met.
However, a customer would still need to choose an automation platform
and take it into use.
> OCP4: Add response for CM-2(2)

- openshift-container-platform-4/policies/CM-Configuration_Management/component.yaml
This controls really is not applicable.
> OCP4: Add responses to CM-3

- openshift-container-platform-4/policies/CM-Configuration_Management/component.yaml
> OCP4: Add response to CM-4(1)

- openshift-container-platform-4/policies/CM-Configuration_Management/component.yaml
> OCP4: Add response for CM-5(1)

- openshift-container-platform-4/policies/SI-System_and_Information_Integrity/component.yaml
> OCP4: Add reponse for SI-12

- openshift-container-platform-4/policies/CM-Configuration_Management/component.yaml
> OCP4: Add response for CM-6(1)

- openshift-container-platform-4/policies/CM-Configuration_Management/component.yaml
> OCP4: Add response for CM-5(3)

- openshift-container-platform-4/policies/AC-Access_Control/component.yaml
@carlosmmatos  @JAORMX do you agree that the screen lock
with a pointer to configuring the inactivity timeout
is the way to go?
> OCP AC-11: Not applicable, configure screen lock

- openshift-container-platform-4/policies/CM-Configuration_Management/component.yaml
> OCP4: Add response to CM-5(5)

- openshift-container-platform-4/policies/CM-Configuration_Management/component.yaml
> OCP4: Add response to CM-6

- openshift-container-platform-4/policies/AC-Access_Control/component.yaml
Reverts ComplianceAsCode/redhat#1301
> Revert "OCP AC-10"

- openshift-container-platform-4/policies/AC-Access_Control/component.yaml
While the conditions to disconnect the users are organizationally
defined, the condition to disconnect after a period of time (e.g.
at the end of the day) is so common that it should be mentioned
explicitly.
> OCP AC-12: Describe token max age configuration

- openshift-container-platform-4/policies/CM-Configuration_Management/component.yaml
NetworkPolicies are the answer (mostly)
> OCP4: Add response for CM-7

- openshift-container-platform-4/policies/AU-Audit_and_Accountability/component.yaml
Card that tracks CaC rule:
https://issues.redhat.com/browse/CMP-963
> OCP AU-4: Link to partitioning documentation

- openshift-container-platform-4/policies/CM-Configuration_Management/component.yaml
It's not applicable, but I added docs to help people create inventories.
> OCP4: Add response for CM-8

- openshift-container-platform-4/policies/SA-System_and_Services_Acquisition/component.yaml
The organization requires the developer of the information system,
system component, or information system service to provide a description
of the functional properties of the security controls to be employed.
> OCP4 SA-4(1): Link to the OpenShift security guide

- openshift-container-platform-4/policies/SA-System_and_Services_Acquisition/component.yaml
The organization requires the developer of the information system,
system component, or information system service to identify early in the
system development life cycle, the functions, ports, protocols, and
services intended for organizational use.
> OCP SA-4(9): Document the network requirements

- openshift-container-platform-4/policies/SA-System_and_Services_Acquisition/component.yaml
> OCP SA-5: Security documentation for admins and users

- openshift-container-platform-4/policies/SA-System_and_Services_Acquisition/component.yaml
The organization requires the developer of the information system,
system component, or information system service to provide design and
implementation information for the security controls to be employed that
includes: [Selection (one or more): security-relevant external system
interfaces; high-level design; low-level design; source code or hardware
schematics; [Assignment: organization-defined design/implementation
information]] at [Assignment: organization-defined level of detail].
> OCP: SA-4(2): Link to documentation, github and REST API docs

- openshift-container-platform-4/policies/IA-Identification_and_Authentication/component.yaml
> OCP4: Answer IA-8 controls

- openshift-container-platform-4/policies/CM-Configuration_Management/component.yaml
Address whitelisting through image-signing enforcement in the container
runtime.
> OCP4: Answer CM-7(5)

- openshift-container-platform-4/policies/CM-Configuration_Management/component.yaml
> OCP4: Response to CM-7(2)

- openshift-container-platform-4/policies/SA-System_and_Services_Acquisition/component.yaml
The organization requires the developer of the information system,
system component, or information system service to produce a plan for
the continuous monitoring of security control effectiveness
CaC follow-up card:
https://issues.redhat.com/browse/CMP-971
> OCP4: SA-4 (8): Continuous monitoring of security control effectiveness

- openshift-container-platform-4/policies/IA-Identification_and_Authentication/component.yaml
This gets picked up by our automation.
> OCP4: Amend response for IA-6

- openshift-container-platform-4/policies/AU-Audit_and_Accountability/component.yaml
The combination of the audit being on by default and what the profiles
log makes the control met by default.
> OCP4: AU-12 is inherently met

- openshift-container-platform-4/policies/AC-Access_Control/component.yaml
A CaC rule is tracked as https://issues.redhat.com/browse/CMP-935 and
https://issues.redhat.com/browse/CMP-964
> OCP4: reply to AC-4 and AC-4(21)

- openshift-container-platform-4/policies/IA-Identification_and_Authentication/component.yaml
This is inherently met, let's add a blob that makes it clear to our
automation.
> OCP4: IA-5(5): Password feedback obfuscation

- openshift-container-platform-4/policies/AU-Audit_and_Accountability/component.yaml
The control was already tagged in CaC, I just forgot to send the opencontrol
reply.
> OCP4 AU-6(1): CLO is the answer

- openshift-container-platform-4/policies/IA-Identification_and_Authentication/component.yaml
IDP control
The control is already tagged correctly in CaC, I just forgot to send the
opencontrol reply.
> OCP4: IA-5(4): Password complexity

- openshift-container-platform-4/policies/SC-Systems_and_Communications_Protection/component.yaml
> OCP4: Add responses for most SC-7 controls needed for FedRAMP moderate

- openshift-container-platform-4/policies/SA-System_and_Services_Acquisition/component.yaml
The organization requires the developer of the information system, system component, or information system service to:
a. Perform configuration management during system, component, or service [Selection (one or more): design; development; implementation; operation];
b. Document, manage, and control the integrity of changes to [Assignment: organization-defined configuration items under configuration management];
c. Implement only organization-approved changes to the system, component, or service;
d. Document approved changes to the system, component, or service and the potential security impacts of such changes; and
e. Track security flaws and flaw resolution within the system, component, or service and report findings to [Assignment: organization-defined personnel].
> OCP4: SA-10: developer configuration management

- openshift-container-platform-4/policies/SA-System_and_Services_Acquisition/component.yaml
> OCP4: Add response for SA-10(1)

- openshift-container-platform-4/policies/CA-Security_Assessment_and_Authorization/component.yaml
This control is inherently met because mTLS is used for the control
plane.
> CA-9: Internal system connections

- openshift-container-platform-4/policies/CA-Security_Assessment_and_Authorization/component.yaml
> OCP4: Mark CA-9 as complete

- openshift-container-platform-4/policies/IA-Identification_and_Authentication/component.yaml
The control was discussed at length at:
https://issues.redhat.com/browse/CMP-982
> OCP4: IA-5(7): unencrypted static authenticators

- openshift-container-platform-4/policies/RA-Risk_Assessment/component.yaml
Most of these will not be addressed by OpenShift itself, but instead by
third party products.
> OCP4: Add responses for RA-5

- openshift-container-platform-4/policies/SI-System_and_Information_Integrity/component.yaml
> OCP4: SI-4 (23) response is inherently met.

- openshift-container-platform-4/policies/SA-System_and_Services_Acquisition/component.yaml
A sanitized version of reply from prodsec, the full reply can be found
at https://issues.redhat.com/browse/CMP-1003
> SA-11(1) reply
